tegra-storage-layout: fixes for jetpack 5
To share the same storage layout we need to convert EXT_NUM_SECTORS
used on jetpack 6 to NUM_SECTORS used on Jetpack 5.

Prevents tegraflash failures with
```
[   6.1643 ] Number of sectors is zero for sdmmc_user: 3 device
Error: Return value 4
```
which happen because the num_sectors field in the external-flash.xml
file are malformed like this:
```
<device type="sdmmc_user" instance="3" sector_size="512" num_sectors="EXT_122159104">
```